#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
  - npm install -g @angular/cli

after_success:
  - npm run coveralls

script:
  - ng lint
  - ng test --watch false --cc
  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change
